export const START_GAME = 'START_GAME';
export const SELECT_NUMBER = 'SELECT_NUMBER';
export const UPDATE_COMPLETE_LINE = 'UPDATE_COMPLETE_LINE';
export const SHOW_MODAL = 'SHOW_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';